# Generated by Django 5.0.14 on 2025-11-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pendinguser_remove_customuser_sms_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
