# Generated by Django 5.2.1 on 2025-06-02 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_interest_purpose_userprofile_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_requests_limit', models.PositiveIntegerField(default=50)),
                ('requests_left', models.PositiveIntegerField(default=50)),
                ('last_reset', models.DateTimeField(auto_now_add=True)),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='blocked_by', to='users.userprofile')),
                ('requests', models.ManyToManyField(blank=True, related_name='requested_profiles', to='users.userprofile')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribed_to', to='users.userprofile')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='users.userprofile')),
            ],
        ),
    ]
