# Generated by Django 5.2.6 on 2025-10-14 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userimage',
            name='unique_main_image_per_user',
        ),
        migrations.AlterField(
            model_name='userimage',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='users.userprofile'),
        ),
    ]
