# Generated by Django 5.2.6 on 2025-10-16 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_userimage_unique_main_image_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
