# Generated by Django 5.2.6 on 2025-10-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userimage_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.userprofile'),
        ),
    ]
